Add BaseProgram example. Support 'approve' and 'revoke' instructions …
defactojob/solray pull request #3
Opened 2020-11-21 23:11 UTC by czl1378

…for SPLToken. #1

2020-11-22 02:06 UTC, defactojob reviewed
looks good

i think we refine the multisigner API

2020-11-22 02:06 UTC, defactojob commented on src/SPLToken.ts
> +    }
maybe we could extend `InstructionAuthority` to consider `Account[]` or `PublicKey[]` as a multisigners.

we see the multisigners pattern in many token instructions.

then this method boils down to:

```ts
this.instructionEncode(layout, { instruction: 5 }, [
   revokeAuthority || multiSigners
]);
```

2020-11-22 02:06 UTC, defactojob commented on src/SPLToken.ts
> +    if (multiSigners.length === 0) {
see comment below, for an idea how to abstract multiSigners better.

2020-11-22 02:06 UTC, defactojob commented on src/SPLToken.ts
> +  multiSigners: Array<Account>,
let's use `T[]` to declare array types

2020-11-22 02:06 UTC, defactojob commented on src/BaseProgram.ts
> +      preflightCommitment: 'singleGossip',
instead of hardwiring `singleGossip`, we could read these from this.conn (I believe)

2020-11-22 02:06 UTC, defactojob commented on src/BPFLoader.ts
> +    );
maybe we add a linter to standardize ; or not

2020-11-22 02:15 UTC, defactojob requested changes

2020-11-22 02:15 UTC, defactojob commented on src/index.ts
> +        return new Connection("http://localhost:8899", commitment as any)
how about let's change the API to:

```
connect("dev")
connect("http://localhost:8899")
```

and "local" aliases to "http://localhost:8899"

2020-11-22 03:30 UTC, czl1378 commented on src/BaseProgram.ts
> +      preflightCommitment: 'singleGossip',
After some testing, I found that if we do not specify  `preflightCommitment` or `skipPreflight` here,  will cause the error: `Transaction simulation failed: Attempt to load a program that does not exist `.

2020-11-22 03:56 UTC, defactojob commented on src/BaseProgram.ts
> +      preflightCommitment: 'singleGossip',
i mean you can change it to:

```
commitment: this.conn.commitment,
preflightCommitment: this.conn.commitment,
```

2020-11-22 04:05 UTC, czl1378 commented on src/SPLToken.ts
> +    }
good idea, i will consider to implement this

2020-11-22 04:10 UTC, czl1378 commented on src/BaseProgram.ts
> +      preflightCommitment: 'singleGossip',
Okay.

2020-11-22 07:53 UTC, czl1378 commented on src/index.ts
> +        return new Connection("http://localhost:8899", commitment as any)
maybe next update.

2020-11-23 01:21 UTC, defactojob requested changes

2020-11-23 01:21 UTC, defactojob commented on src/index.ts
> +export { default as System } from "./System"
let's ban default exports. sorry.

2020-11-23 01:21 UTC, defactojob commented on src/SPLToken/index.ts
> +import { TransactionInstruction, SYSVAR_RENT_PUBKEY } from '@solana/web3.js';
please move `SPLToken/index.ts -> SPLToken.ts`.

impossible to code review now.

2020-11-23 01:21 UTC, defactojob commented on src/SPLToken/types.ts
> +  multiSigners: Account[]
I think it'd be more concise to just combine these together.

```
authority: Account | Account[]
```

The authority cannot be PublicKey, but it needs to be a signer.

2020-11-23 03:27 UTC, defactojob approved these changes

2020-11-23 03:28 UTC, merged